### ISSUE TITLE
Validate via Vee-Validate?

### ISSUE THREAD

**Issue by koddr** [cezardasilva/vue-simple-upload-component#1]
Hello. Thanks for component!

Some question here... How can I validate upload field via Vee-Validate and send with submit form? Examples are welcome 👍

**Comment by cezardasilva** [comment]
Hello @koddr ! 

You can't validate via Vee-Validate (but it's a good point, i'll put this on component roadmap). however you can validate file extension via component props. Like this: 

```
<upload-file :acceptedFormats="['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/msword']"</upload-file> 
```

About the other question: "..send with submit form?": The component idea's the simplicity, then i dont dev this function yet.

**Comment by koddr** [comment]
@cezardasilva thanks for answers 👍 Hope in future good stuff from you!
